### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by michaellampert** [MelleD/ha-radar-warning#10]
Hi,

when i setup the Service (0.4.1)

i get the this Error 

2024-10-11 08:21:24.623 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Radar for radar_warnings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/radar_warnings/__init__.py", line 14, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/config/custom_components/radar_warnings/coordinator.py", line 58, in async_config_entry_first_refresh
    await self._async_update_data()
  File "/config/custom_components/radar_warnings/coordinator.py", line 63, in _async_update_data
    await self.api.update_pois()
  File "/config/custom_components/radar_warnings/radar_api.py", line 206, in update_pois
    pois = await self.get_pois()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/radar_warnings/radar_api.py", line 189, in get_pois
    vmax=poi_data['vmax'],
         ~~~~~~~~^^^^^^^^
KeyError: 'vmax'

And i doesn't have an idea how to fix this

**Comment by MelleD** [comment]
Looks not that is related to the previous version, because it's the same code, but you can try the previous version off course.

Looks more your response have no vmax, but without the Info it make less sense, right?

**Comment by MelleD** [comment]
Try version 0.4.2
